### ISSUE TITLE
addcolumninlist problem when turning to next page

### ISSUE THREAD

**Issue by ilosamos** [FuenRob/Modules-Prestashop-1.7#1]
Hi,

thanks for your plugin addcolumninlist, it really helped me a lot, but unfortunately I have a very annoying problem.
I slightly modified and simplified the plugin because I just wanted to add the "location" column to the products listing in the back office. It works just fine. Displaying and filtering looks good.
However when the filtering results in many rows and i want to click on the next page, the filtering is gone. It turns to the second page but deletes my custom "location" filtering and then displays all products instead.

I'll attach my version of the plugin. I would highly appreciate your help!!!

Thanks in advance!
[addcolumninlist_modified.zip](https://github.com/FuenRob/Modules-Prestashop-1.7/files/2523269/addcolumninlist_modified.zip)

**Comment by FuenRob** [comment]
Hi,

In my Prestashop's version, 1.7.4.3, I need edit this files:
**/src/Adapter/Product/AdminProductDataProvider.php**
With this code in the function: **public function getCatalogProductList** after **'active' => array('table' => 'sa', 'field' => 'active', 'filtering' => self::FILTERING_EQUAL_NUMERIC),**:
`'location' => array('table' => 'p', 'field' => 'location'),`

And in this file:
**/src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Forms/form_products.html.twig** add after: **'filter_column_active':filter_column_active,** this code:
`'filter_column_location' : filter_column_location,`

And in this file:
**/src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/catalog.html.twig** add after: **'filter_column_active':filter_column_active,** this code:
`'filter_column_location' : filter_column_location,`

Please, tell me your progress

Thanks

**Comment by ilosamos** [comment]
Hi,

thanks for your Answer!
Im on Prestashop version 1.7.3.1 (sry for not mentioning)

I found the first file and made the changes.

Unfortunately the files **form_products.html.twig** and **catalog.html.twig** are not there. The **CatalogPage** directory is not even existing in my version.

Thanks

**Comment by FuenRob** [comment]
hi,
Please, uninstall the old module in installs that attached.

Inside this module there is an **AdminFilter.php file** in:

**addcolumninlist/Entity/PrestaShop/AdminFilter.php**

Replace that file with the one in:

**src/PrestaShopBundle/Entity/AdminFilter.php**

With this is enough.

I hope it works for you.

Thank you.

[addcolumninlist_solved.zip](https://github.com/FuenRob/Modules-Prestashop-1.7/files/2545874/addcolumninlist_solved.zip)

**Comment by ilosamos** [comment]
Hi,

I did as you instructed but unfortunately it doesnt work. Now the additional filtering column for the location (Regal) field is totally gone in article listing (see screenshots attached).
That's probably because you disabled **displayAdminCatalogTwigProductHeader** and **displayAdminCatalogTwigProductFilter** hooks.
What was the goal by removing the registering for those 2 hooks?

![capture](https://user-images.githubusercontent.com/9646181/47970544-363d6480-e087-11e8-8584-5ce76a4ea4f2.PNG)

Kind regards,
Daniel

**Comment by ilosamos** [comment]
Hi,

thanks for you answer. Now the filtering stays when turning to other pages but however the text in the filtering header does not stay there. The textfield is empty when going to page "2" for example.
So here's what the filtering looks like on page 1:
![capture](https://user-images.githubusercontent.com/9646181/47970656-eb245100-e088-11e8-8cd9-c8988b5462a8.PNG)

Because the result of the filtering are 300 rows i go to page 2. It still does filter the correct value but the textfield is blank:
![capture](https://user-images.githubusercontent.com/9646181/47970674-1a3ac280-e089-11e8-8417-4b8f85702060.PNG)

And another thing: Why did you remove those 2 hooks **displayAdminCatalogTwigProductHeader** and 
**displayAdminCatalogTwigProductFilter**. When i remove those the header and textfield of the filtering are completely gone.

Thanks for your help!

**Comment by FuenRob** [comment]
Hi,

We use those two hooks to add the filter, but now we have edited the files: **catalog.html.twig and list.html.twig**, but now we do not use these hooks. When you install the module, it must override these files.

With the version of the module that i attach in the previous comment and editing the file: **src/PrestaShopBundle/Entity/AdminFilter.php**, it works well. I attached a picture.

Thanks

![img-pic-probe](https://user-images.githubusercontent.com/7713007/48052393-15b8fb80-e1a8-11e8-9bcc-a7891d8daf67.png)

**Comment by ilosamos** [comment]
That's it!
Thanks so much for your help!

If I wanted to update my prestashop version the changes in **src/PrestaShopBundle/Entity/AdminFilter.php** would be overwritten is that correct?

**Comment by FuenRob** [comment]
That's right. You should change the files indicated in previous comments.

**Comment by ilosamos** [comment]
Alright thanks!
